info:
  app:
    name: notification-service
    description: Sample RabbitMQ App
    version: 1.0-SNAPSHOT
  company:
    name: Somekind Software

logging:
  level:
    root: INFO
    ru.dgorokhov: DEBUG
    org.springframework.web: INFO
    org.springframework.validation: INFO

management:
  endpoints.web.exposure.include: health,info,metrics
  endpoint.health.show-details: always
  metrics.export.prometheus.enabled: true
  info.env.enabled: true

server:
  port: 8081
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  rabbitmq:
    host: localhost
    port: 5672
    username: mrrabbit
    password: veryverysecretword
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 2s
        concurrency: 3
        max-concurrency: 10
        prefetch: 1
        declare: true
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  properties:
    notification-fanout: user.events.fanout
    notification-queue-postfix: notify.queue
  email:
    provider: javamail
